// <auto-generated/>
global using global::System;
global using global::System.Collections.Generic;
global using global::System.IO;
global using global::System.Linq;
global using global::System.Net.Http;
global using global::System.Text;
global using global::System.Threading;
global using global::System.Threading.Tasks;

global using global::Microsoft.Extensions.Configuration;
global using global::Microsoft.Extensions.Configuration.CommandLine;
global using global::Microsoft.Extensions.Configuration.EnvironmentVariables;
global using global::Microsoft.Extensions.Configuration.Json;
global using global::Microsoft.Extensions.Configuration.Memory;
global using global::Microsoft.Extensions.DependencyInjection;
global using global::Microsoft.Extensions.Options;

global using global::Microsoft.PowerPlatform.Dataverse.Client;
global using global::Microsoft.PowerPlatform.Dataverse.Client.Model;

global using global::Brimborium.Registrator;

global using global::Brimborium.Werkzeugkasten.Library;


